library(zoo)
library(forecast)
library(TSstudio)

# jak cos to to jest plik na jakiś mój rózny syf,
# ale najważniejsze rzeczy przeklejam do data_setup
#getwd()
setwd("/Users/magdalenapotok/Desktop/japan_travel/data")
japan_dt <- readRDS("japan_dt.RDS")
str(japan_dt)
japan_zoo <- zoo(japan_dt$visitors, japan_dt$date) #tworzy obiekt serii czasowej, visitors to dane, date indeks czasowy
japan_ts <- ts(japan_zoo, start = 1990, frequency = 12)
plot(japan_ts)
japan_spencer = filter(japan_ts, 1/320 * c(-3, -6, -5, 3, 21, 46, 67, 74, 67, 46, 21, 3, -5, -6, -3), sides = 2)
plot(japan_ts)
plot(japan_spencer)
lines(japan_spencer, col = "red")
plot(ma(japan_ts, order =8 ))
str(japan_ts)
Acf(japan_ts, lag = 60)
ts_decompose(japan_ts)
Pacf(japan_ts, lag = 60)
class(japan_ts)
japan_filtered <- window(japan_ts, start=c(2010, 1), end=c(2019, 12))
class(japan_filtered)
# tu już ładnie widać sezonowość :)
plot(japan_filtered, main="Turystyka w Japonii (2010-2019)", xlab="Czas", ylab="Liczba turystów")
decompose(japan_filtered)
japan_dt_filtered = japan_dt[japan_dt$date > as.Date("2009-12-31") & japan_dt$date < as.Date("2020-01-01") ]

plot_ly(japan_dt_filtered[order(japan_dt_filtered$date), ], x = ~date, y = ~visitors, type = 'scatter', mode = 'lines')
ts_decompose(japan_filtered)
japan_covid <- window(japan_ts, start=c(2010, 1), end=c(2024, 12))
plot(japan_covid, main="Turystyka w Japonii (2010-2024)", xlab="Czas", ylab="Liczba turystów")
ts_decompose(japan_covid)
